services:
  db:
    image: postgres:latest
    container_name: trh-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - -c
      - wal_level=logical
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trh-network

networks:
  trh-network:
    driver: bridge

volumes:
  postgres-data:
